### ISSUE TITLE
trigger 

### ISSUE THREAD

**Issue by SamanehShamshiri** [YukiM00/Backdoored-COVID-Net#5]
y_testb = []
    predb = []
    for i in range(len(testfile)):
        lineb = testfile[i].split()
        xb = process_image_file(os.path.join(testfolder, lineb[1]), 0.08, input_size)
        xb = make_trigger(xb)
        xb = xb.astype('float32') / 255.0
        y_testb.append(mapping[lineb[2]])
        predb.append(np.array(sess.run(pred_tensor, feed_dict={image_tensor: np.expand_dims(xb, axis=0)})).argmax(axis=1))
    y_testb = np.array(y_testb)
    predb = np.array(predb)
 
would you please explain why you make triggers for the test folder?
Thank you very much

**Comment by kztakemoto** [comment]
This is simply to evaluate the performance of backdoor attacks on test images (e.g., see the bottom panels of Fig. 2 in [our paper](https://www.mdpi.com/2076-3417/11/20/9556)).
